### ISSUE TITLE
What is the minimum time_step duration?

### ISSUE THREAD

**Issue by baballev** [yannbouteiller/rtgym#1]
For most environments, the time.sleep() python function does not provide a precise way of measuring and waiting for small time duration and fluctuates between different operating systems; Have you tested the library for very short time steps? I would like to know if there has been some tests for durations inferior to the ones made in the test script. Thanks in advance for your answer!

**Comment by yannbouteiller** [comment]
Hi, I have not tested time-steps smaller than 0.02s yet. My current projects using rtgym are clocked between 20Hz and 50Hz, but I am interested in knowing what the smallest reasonable time-granularity is right now. If you experience with this please share your results. If someone has ideas for optimizing it further, this will be welcome too.

You are right, so far time.sleep() is used by the clocking thread to wait for the remaining duration of the time-step.

**Comment by baballev** [comment]
Ok, thank you for your answer, I'll be sure to comment here if I experience any issues for high frequencies.

**Comment by yannbouteiller** [comment]
Hi, following on this, we have conducted [benchmark experiments](https://github.com/yannbouteiller/rtgym#performance) on Windows and Linux.

Turns out the minimum duration is highly OS-dependent. On Windows, anything below 50Hz (0.02s) is unreasonable, whereas on Linux you can easily go down to 500Hz (0.002s).

Probably a real-time OS can perform at an even higher frequency.
